### ISSUE TITLE
cpunodebind fails with "numa_sched_setaffinity_v2_int() failed: Invalid argument" error message.

### ISSUE THREAD

**Issue by Naresh-ibm** [numactl/numactl#127]
getting following error while trying to do cpunodebind using numactl,

localhost:~ # numactl --cpunodebind=0 --membind=1 dd if=/dev/zero of=/dev/mapper/360050768108001b3a80000000000010b bs=1M count=1024
numa_sched_setaffinity_v2_int() failed: Invalid argument
sched_setaffinity: Invalid argument
localhost:~ #

logs
------------
llocalhost:~ # numactl -H
available: 4 nodes (0-3)
node 0 cpus:
node 0 size: 8664 MB
node 0 free: 2650 MB
node 1 cpus:
node 1 size: 5602 MB
node 1 free: 5587 MB
node 2 cpus: 0 1 2 3 4 5 6 7
node 2 size: 0 MB
node 2 free: 0 MB
node 3 cpus:
node 3 size: 1023 MB
node 3 free: 123 MB
node distances:
node   0   1   2   3 
  0:  10  20  20  20 
  1:  20  10  20  20 
  2:  20  20  10  20 
  3:  20  20  20  10 
localhost:~ #

localhost:~ # numactl --cpunodebind=2  dd if=/dev/zero of=/dev/mapper/360050768108001b3a80000000000010b bs=1M count=1024
libnuma: Warning: node argument 2 is out of range
<2> is invalid
localhost:~ #

===>>For other nodes it gives following errors .

localhost:~ # numactl --cpunodebind=0  dd if=/dev/zero of=/dev/mapper/360050768108001b3a80000000000010b bs=1M count=1024
numa_sched_setaffinity_v2_int() failed: Invalid argument
sched_setaffinity: Invalid argument
localhost:~ # numactl --cpunodebind=1  dd if=/dev/zero of=/dev/mapper/360050768108001b3a80000000000010b bs=1M count=1024
numa_sched_setaffinity_v2_int() failed: Invalid argument
sched_setaffinity: Invalid argument

**Comment by Naresh-ibm** [comment]
[Uploading supportconfig_numactl_issue_puntfish_Sles15sp3.zip…]()

**Comment by luochenglcs** [comment]
`localhost:~ # numactl --cpunodebind=1 dd if=/dev/zero of=/dev/mapper/360050768108001b3a80000000000010b bs=1M count=1024
numa_sched_setaffinity_v2_int() failed: Invalid argument
sched_setaffinity: Invalid argument`
----
>I think it is because there is no cpu on node1, numa_node_to_cpus function cpumap is zero, so sched_setaffinity returns Invalid argument.

`localhost:~ # numactl --cpunodebind=2 dd if=/dev/zero of=/dev/mapper/360050768108001b3a80000000000010b bs=1M count=1024
libnuma: Warning: node argument 2 is out of range
<2> is invalid`
----
>I think it is because there is no memory available on node2, the numa_init->set_task_constraints function gets the available node through /proc/self/status, and there is no node2 in it, so node2 is not in the available range, which is reasonable.

**Comment by watologo1** [comment]
I agree with the first (no CPU avail on cpunodebind used NUMA node)
But for the latter (cpunodebind NUMA node has no memory), it could/should fall back to make use of memory of other nodes.

Can this be tested please:
In case Node 0 has no memory, this should work?:
numactl --cpunodebind=0 --membind=0,1 process Run process on node 0 with memory allocated on node 0 and 1.

This as well?:
numactl --cpunodebind=0 --balancing --membind=0,1 process Run process on node 0 with memory allocated on node 0 and 1.

The solution could be to fallback to this (does this work with no memory on CPU 0):
numactl -a --cpunodebind=0 ls

**Comment by watologo1** [comment]
Wait, the first 2 tests would show the same errors, you always would have to add:
-a (or --all)
Paramter as the first one, e.g.:
numactl -a --cpunodebind=0 --membind=0,1 ls

If this works, my idea would be to fallback to this behaviour automatically.

**Comment by andikleen** [comment]
This should be fixed in the latest version
