### ISSUE TITLE
General question on `numa_run_on_node`

### ISSUE THREAD

**Issue by ikabadzhov** [numactl/numactl#129]
I was reading:
```
/* Run current task only on node */
int numa_run_on_node(int node);
```
I would like to make sure that I have a correct understand of this. What does "task" refer in this case - is it also threads?

My goal is to split different threads (from the tbb arena) of the same process to different NUMA domains. Currently what I do is:
1. spawn 1 thread for each NUMA domain
2. for each thread restrict it to a different NUMA domain as:
```
numa_run_on_node(i);
numa_run_on_node_mask(numa_all_nodes_ptr);
```
3. From each thread spawn X threads, where X is the number of cores inside of each domain.

Does that make sense?

**Comment by luochenglcs** [comment]
First, it is clear that `task` refers to thread.

from numa manuals：
`  numa_run_on_node()  runs  the  current task and its children on a specific node. They will not migrate to CPUs of other nodes until the node affinity is reset with a new call to  numa_run_on_node_mask().  Passing -1 permits the kernel to schedule on all nodes again.  On success, 0 is returned; on error -1 is returned, and errno is set to indicate the error.`

1.  spawn 1 thread for each NUMA domain, for each thread restrict it to a different NUMA domain as:
`numa_run_on_node(i);`
---
> This restricts the thread and its children to run only on the CPU of the specified node.

2、From each thread spawn X threads, where X is the number of cores inside of each domain.
---
> The child thread inherits the attributes of its parent thread and can run only on the CPU of the specified node.

I think this will meet your requirements.

**Comment by ikabadzhov** [comment]
Thank you very much for your quick response!
