### ISSUE TITLE
New version?🤔

### ISSUE THREAD

**Issue by kloczek** [numactl/numactl#130]
Looking on https://github.com/numactl/numactl/compare/v2.0.14...master I think that it would be good to flush all those changes as new release 😋

**Comment by andikleen** [comment]
Yes good point. Thanks. A tagged a new release.

**Comment by filbranden** [comment]
@andikleen It seems you missed updating the version in [configure.ac](https://github.com/numactl/numactl/blob/v2.0.15/configure.ac#L2).

We could fix that by either dropping the current tag/release, shipping a commit to update the version and tagging that one with v2.0.15, or we could create a new v2.0.16 (to avoid confusion of v2.0.15 pointing to two different commits at two points in time.)

What do you think? I'm happy to do push a commit, add the tag, create the release, etc. (Also create a tarball that includes the generated autotools scripts and upload them to the release), just let me know which plan sounds better to you and I can take it from there.

(Also, I liked your GitHub workflow ideas! Let me look into automating cutting a release, including updating the version in configure.ac as well.)

**Comment by andikleen** [comment]
On Fri, Sep 09, 2022 at 11:58:02AM -0700, Andi Kleen wrote:
> On Fri, Sep 09, 2022 at 08:49:23AM -0700, Filipe Brandenburger wrote:
> > @andikleen It seems you missed updating the version in configure.ac.
> > 
> > We could fix that by either dropping the current tag/release, shipping a commit
> > to update the version and tagging that one with v2.0.15, or we could create a
> > new v2.0.16 (to avoid confusion of v2.0.15 pointing to two different commits at
> > two points in time.)
> 
> Let's do a v2.0.16
> 
> > 
> > What do you think? I'm happy to do push a commit, add the tag, create the
> > release, etc. (Also create a tarball that includes the generated autotools
> > scripts and upload them to the release), just let me know which plan sounds
> > better to you and I can take it from there.
> 
> Sure please do it.
> 
> > (Also, I liked your GitHub workflow ideas! Let me look into automating cutting
> > a release, including updating the version in configure.ac as well.)
> 
> That would be nice indeed.

Looks like we have to do a new release anyways to fix #135

**Comment by filbranden** [comment]
@andikleen Are we ready to release v2.0.16 or do any other fixes need to go in before that?

Part of the automation from #140 is already in place, so to create a new release (including autogen'd tarball and GitHub release) all we need is to bump up VERSION and push a tag with it:

```
$ echo 2.0.16 >VERSION
$ git commit -am 'Release numactl 2.0.16'
$ git tag -a v2.0.16 -m 'Release numactl 2.0.16'
$ git push origin v2.0.16
```

I'm happy to go ahead and do that if we're ready for 2.0.16, or just go ahead whenever you're ready.

**Comment by filbranden** [comment]
@andikleen Ping? Are we good to release 2.0.16 now, or do we need any other commits to make it in at this point?

I'm leaning towards creating the release, if it turns out there are more fixes that are needed, we can release a new version again (2.0.17 then?) but I'll wait until tomorrow to hear back from you on this. Thanks!

**Comment by andikleen** [comment]
On Mon, Oct 03, 2022 at 02:25:46PM -0700, Filipe Brandenburger wrote:
> @andikleen Ping? Are we good to release 2.0.16 now, or do we need any other
> commits to make it in at this point?
> 
> I'm leaning towards creating the release, if it turns out there are more fixes
> that are needed, we can release a new version again (2.0.17 then?) but I'll
> wait until tomorrow to hear back from you on this. Thanks!

We should be fine for a release now. Thanks

**Comment by filbranden** [comment]
v2.0.16 released! 🎉 

https://github.com/numactl/numactl/releases/tag/v2.0.16

**Comment by andikleen** [comment]
On Fri, Sep 09, 2022 at 08:49:23AM -0700, Filipe Brandenburger wrote:
> @andikleen It seems you missed updating the version in configure.ac.
> 
> We could fix that by either dropping the current tag/release, shipping a commit
> to update the version and tagging that one with v2.0.15, or we could create a
> new v2.0.16 (to avoid confusion of v2.0.15 pointing to two different commits at
> two points in time.)

Let's do a v2.0.16

> 
> What do you think? I'm happy to do push a commit, add the tag, create the
> release, etc. (Also create a tarball that includes the generated autotools
> scripts and upload them to the release), just let me know which plan sounds
> better to you and I can take it from there.

Sure please do it.

> (Also, I liked your GitHub workflow ideas! Let me look into automating cutting
> a release, including updating the version in configure.ac as well.)

That would be nice indeed.

Thanks,
-Andi
