### ISSUE TITLE
numactl --localalloc on Mysql

### ISSUE THREAD

**Issue by Leox0717** [numactl/numactl#143]
I run mysql on 2*Intel 6226 Server.

When I use `numactl -N 0 --localalloc` to start mysql service I find that the memory from node 1 is be used, which is different from using option `numactl -N 0 -m 0`.

Please help explain why this happens

Much thanks！

You can check the relevant picture on [https://stackoverflow.com/questions/74150391/numactl-localalloc-on-mysql]()

**Comment by luochenglcs** [comment]
--localalloc ：Preferably allocate memory on local node, but if memory cannot	be allocated there fall back to other nodes,  like --preferred local node,  it is kernel default mempolicy.

so `numactl -N 0 --localalloc` is more like `umactl -N 0 --preferred 0`;

but `numactl -N 0 -m 0`  mean   only  allocate  memory  from  nodes,  Allocation will fail when there is not enough memory available on nodes.

**Comment by luochenglcs** [comment]
kernel code：
do_set_mempolicy/__do_mbind
   ->mpol_new // set mempolicy

`static struct mempolicy *mpol_new(unsigned short mode, unsigned short flags,
				  nodemask_t *nodes)
{
   ...
  	} else if (mode == MPOL_LOCAL) {
		if (!nodes_empty(*nodes) ||
		    (flags & MPOL_F_STATIC_NODES) ||
		    (flags & MPOL_F_RELATIVE_NODES))
			return ERR_PTR(-EINVAL);
		mode = MPOL_PREFERRED; 
}`
