### ISSUE TITLE
Fail gracefully if sysfs is not mounted

### ISSUE THREAD

**Issue by Xyene** [numactl/numactl#161]
Currently, linking `libnuma` causes applications to fail at runtime if executed on a system without sysfs mounted, even if the application takes care to not attempt to use `libnuma` on such a system. This is because `numa_init` is a static constructor, which ends up calling some functions that call `exit(1)` on error if sysfs isn't present.

This makes it very hard to write portable applications using `libnuma`, without resorting to `dlopen`-ing `libnuma` manually once it is known that sysfs is present.

A case where `libnuma` may be installed without sysfs being present is within containers, such as those created by [bubblewrap](https://github.com/containers/bubblewrap), which may be in use to sandbox compilation / unit testing / etc.

A patch like

```diff
diff --git a/src/libnuma.c b/src/libnuma.c
--- a/src/libnuma.c
+++ b/src/libnuma.c
@@ -94,6 +94,13 @@ numa_init(void)
 {         
  int max,i;  
              
+ DIR *sysfs = opendir("/sys");
+ if (sysfs) { 
+   closedir(sysfs);
+ } else { 
+   return;
+ }
+
```

resolves the issue, but is not particularly principled.

It would be great if `libnuma` could behave more gracefully in this case.

**Comment by andikleen** [comment]
I was going to suggest to override numa_err() -- that is how it was originally supposed to be handled -- but unfortunately we have some other bare exit(1)s now. Yes those need to be fixed. I agree it shouldn't exit on sysfs not being mounted.

**Comment by andikleen** [comment]
I fixed it all now, handling the error and removing that one lone exit(1) that should be triggered in this case.

There is another, but it is only triggered for out of memory, which I assume is tolerable.
