### ISSUE TITLE
`check_arg_order` in `test/bind_range` fails on `aarch64`

### ISSUE THREAD

**Issue by jakirkham** [numactl/numactl#163]
Am seeing the `check_arg_order` function from `test/bind_range` fail on Linux `aarch64`.

Here is [the CI build]( https://app.travis-ci.com/github/conda-forge/numactl-feedstock/jobs/595640657 ). Have also [attached the log]( https://github.com/numactl/numactl/files/10702521/cf_numactl_aarch64_fail.txt ) for posterity.

Please let me know if there's anything else needed.

**Comment by andikleen** [comment]
This should be fixed now. I switched to not parse /proc/cpuinfo in the test scripts, but use sysfs/nproc. If  there are still problems let me know.
