### ISSUE TITLE
Add minimum workflow permissions

### ISSUE THREAD

**Issue by gabibguti** [numactl/numactl#166]
Adding minimum permissions to your workflows is important to keep your repository safe against supply-chain attacks. I see your repo has 3 workflows, `Makefile CI`, `CodeQL` and `Create GitHub release from pushed tag`. `Makefile CI` and `CodeQL` should need only `contents: read` access to read your repository code. `Create GitHub release from pushed tag` should need `contents: write` access for the `cut_release` job because the 3P action, `marvinpinto/action-automatic-releases`, needs it to create the release. If you agree, I can open a PR so you can see the changes.

Restricting your workflow permissions is recommended by [GitHub itself](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) and other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

##### Additional context
I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by andikleen** [comment]
Yes please open a pull request with the changes. Thanks.
