### ISSUE TITLE
test/distance uses wrong node names

### ISSUE THREAD

**Issue by harish-24** [numactl/numactl#17]
Test uses the wrong node names by just traversing the number of nodes instead of the actual node names.

Ex:
node 0 8 
is used as node 0 and node 1 and test fails with the following error
```
cd test && ./regress2
./../test/distance
000: 010 000 
001: 1: self distance is not 10 (0)
./../test/distance FAILED!!!!
Makefile:1850: recipe for target 'regress2' failed
make: *** [regress2] Error 1
```
Actual node is 008, hence fails with node value.

**Comment by andikleen** [comment]
Fixed with recent merge

**Comment by harish-24** [comment]
Even with the latest clone, I am hitting the issue. 
```
./../test/distance
000: 010 020 000 000 
001: 020 010 000 000 
002: 2: self distance is not 10 (0)
./../test/distance FAILED!!!!
```

**Comment by andikleen** [comment]
Ok then it was a different issue. Reopening

**Comment by harish-24** [comment]
Closing with #20
