### ISSUE TITLE
Publish numactl-devel for s390x

### ISSUE THREAD

**Issue by v1gnesh** [numactl/numactl#173]
Hi,

I've found that `numactl` and `numactl-libs` are available for install on `s390x`.
However, a `dnf search` doesn't find `numactl-devel`.
Can this be packaged/published for `s390x`, please?

Ref:
https://src.fedoraproject.org/rpms/numactl/blob/rawhide/f/numactl.spec
https://bugzilla.redhat.com/show_bug.cgi?id=1419064
https://rpmfind.net/linux/rpm2html/search.php?query=numactl&submit=Search+...&system=&arch=s390x

**Comment by andikleen** [comment]
On Sat, Apr 01, 2023 at 02:42:35AM -0700, v1gnesh wrote:
>    Hi,
> 
>    I've found that numactl and numactl-libs are available for install on
>    s390x.
>    However, a dnf search doesn't find numactl-devel.
>    Can this be packaged/published for s390x, please?
> 
>    Ref:
>    [1]https://src.fedoraproject.org/rpms/numactl/blob/rawhide/f/numactl.sp
>    ec
>    [2]https://bugzilla.redhat.com/show_bug.cgi?id=1419064
>    [3]https://rpmfind.net/linux/rpm2html/search.php?query=numactl&submit=S
>    earch+...&system=&arch=s390x

Please file a bug against fedora. This project doesn't control the
fedora packaging.

**Comment by v1gnesh** [comment]
Okay, thank you!

**Comment by filbranden** [comment]
It seems Fedora explicitly disables s390 build:
https://src.fedoraproject.org/rpms/numactl/blob/4f5555fd9364bd20614b42c131d7c9c0116b2dad/f/numactl.spec#_14
`ExcludeArch: s390 %{arm}`

Not sure why that is there, it's possible build was broken at some point. @andikleen Is there any reason why this package would not be able to work on s390 (or on ARM architectures, since they're also mentioned)?

**Comment by andikleen** [comment]
On Mon, Apr 03, 2023 at 10:57:04AM -0700, Filipe Brandenburger wrote:
>    It seems Fedora explicitly disables s390 build:
>    [1]https://src.fedoraproject.org/rpms/numactl/blob/4f5555fd9364bd20614b
>    42c131d7c9c0116b2dad/f/numactl.spec#_14
>    ExcludeArch: s390 %{arm}
> 
>    Not sure why that is there, it's possible build was broken at some
>    point. ***@***.*** Is there any reason why this package would not be
>    able to work on s390 (or on ARM architectures, since they're also
>    mentioned)?

Maybe they had an older version where the respective syscall numbers
where not filled in

**Comment by v1gnesh** [comment]
https://en.wikipedia.org/wiki/Linux_on_IBM_Z#Hardware says

_Beginning with Linux kernel version 4.1 released in early 2015, Linux on IBM Z is only available as a 64-bit operating system compatible with z/Architecture mainframes.
Previously Linux on IBM Z was also available as a 32-bit operating system, with 31-bit addressing, compatible with older model mainframes introduced prior to 2000's z900 model.
However, the newer 64-bit Linux kernel and 64-bit Linux on IBM Z distributions are still backward compatible with applications compiled for 32-bit Linux on IBM Z.
Historically the Linux kernel architecture designations were "s390" and "s390x" to distinguish between the 32-bit and 64-bit Linux on IBM Z kernels respectively, but "s390" now also refers generally to the one Linux on IBM Z kernel architecture._


The `arch` command on today's Linux on Z machine returns `s390x`. 
Plus, it seems `numactl`, `numactl-libs`, and `numactl-devel` actually already exist for `s390x`.
https://rpmfind.net/linux/rpm2html/search.php?query=numactl*&submit=Search+...&system=&arch=s390x
I didn't know about this site until recently. I assumed they're not available as I couldn't find them through `dnf` on RHEL9 (couldn't add AppStream, CodeReady Builder source, etc.).
