### ISSUE TITLE
Add Security Policy

### ISSUE THREAD

**Issue by gabibguti** [numactl/numactl#174]
Adding a Security Policy is important to provide guidance on how users can report potential vulnerabilities and when vulnerabilities will be confirmed, fixed and disclosed.

I recently recommended https://github.com/numactl/numactl/issues/166 and, like that change, this one also recommended by [Github](https://docs.github.com/en/code-security/getting-started/securing-your-repository#setting-a-security-policy) and [Scorecard](https://github.com/ossf/scorecard) as a good security practice.

If you agree, I can open a PR to suggest a Security Policy, and we can work together to communicate how the repo can best handle vulnerability reports.

##### Additional Context
Hi again! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by andikleen** [comment]
It's ok to me to open a PR for this, although since libnuma doesn't have any security boundaries and has no secrets it's unclear if there will be actually security bugs.

**Comment by gabibguti** [comment]
Hi @andikleen! C language projects can suffer from memory allocation problems which can then be a port to security attacks. The library itself may not have secrets or internal security boundaries, but it may become a vector for attackers to harm projects that depend on it. For that reason, I'd recommend that you have a security policy for possible reports.
