### ISSUE TITLE
if node 0 is offline, error occurred. preferred-many requested without kernel support

### ISSUE THREAD

**Issue by zikerHe** [numactl/numactl#182]
set_kernel_abi()
     /* Assumes there's always a node 0, and it's online */
	numa_bitmask_setbit(tmp, 0);
it is wrong, if node 0 is limited by cpuset.

##tmp = numa_allocate_nodemask();
tmp = numa_get_mems_allowed();

tmp should be returned by numa_get_mems_allowed() to acquire the allowed node , not node 0.

**Comment by luochenglcs** [comment]
Yes, i totally agree,  and you can try to push patch to fix it.

**Comment by zikerHe** [comment]
> 

https://github.com/numactl/numactl/pull/183
thanks, i have push the patch.
