### ISSUE TITLE
Interleave/Bind fails for empty memory nodes

### ISSUE THREAD

**Issue by gmprice** [numactl/numactl#184]
Pretty simple: if you explicitly select a node that has no memory, interleave/bind will fail.

This appears to be because of a parsing check that limits the "valid" set of interleave/bind nodes to those with memory.

CXL is introducing dynamic capacity devices, which will make sparse nodes (down to 0) a reality.   This limitation should be lifted to allow mempolicy to be set to include memory nodes with 0 capacity.

Alternatively, we could propose a change to the kernel to expose the intent of a node via sysfs instead of parsing `node/meminfo`

Relevant code:

```
int
numa_num_configured_nodes(void)
{
    /*
    * NOTE: this function's behavior matches the documentation (ie: it
    * returns a count of nodes with memory) despite the poor function
    * naming.  We also cannot use the similarly poorly named
    * numa_all_nodes_ptr as it only tracks nodes with memory from which
    * the calling process can allocate.  Think sparse nodes, memory-less
    * nodes, cpusets...
    */
    int memnodecount=0, i;

    for (i=0; i <= maxconfigurednode; i++) {
        if (numa_bitmask_isbitset(numa_memnode_ptr, i))
            memnodecount++;
    }
    return memnodecount;
}
```

```
static void
set_configured_nodes(void)
{
    DIR *d;
    struct dirent *de;
    long long freep;

    numa_memnode_ptr = numa_allocate_nodemask();
... snip ...

            if (numa_node_size64(nd, &freep) > 0)
                numa_bitmask_setbit(numa_memnode_ptr, nd);
... snip ...
}
```

```
/* (cache the result?) */
long long numa_node_size64(int node, long long *freep)
{
    size_t len = 0;
    char *line = NULL;
    long long size = -1;
    FILE *f;
    char fn[64];
    int ok = 0;
    int required = freep ? 2 : 1;

    if (freep)
        *freep = -1;
    sprintf(fn,"/sys/devices/system/node/node%d/meminfo", node);
... snip ...
```

**Comment by luochenglcs** [comment]
I think this issue is the same as the previous issue https://github.com/numactl/numactl/issues/165

**Comment by gmprice** [comment]
I think it's related, yes, but i'm also demonstrating this issue for --interleave. 

The recommendation on that ticket is to use `-a`

```
       --all, -a
              Unset default cpuset awareness, so user can use all possible CPUs/nodes for following policy settings.
```

But this is confusing, because shouldn't --interleave imply this anyway?  I'm telling the system which memory nodes to use, and even if that node has no memory why does it matter?  The kernel will see there's no memory there and allocate from the other nodes.

If a user tries to do something silly like launch without cpu's or launch without memory, the result should be somewhat obvious.  But now that 0-memory nodes (for dynamic capacity) will start becoming a first class feature, this issue is going to show up more and more.

**Comment by andikleen** [comment]
So the problem is that --interleave fails if such a node is present?
I assume you don't really want to interleave on such an empty node, just make the default policies work globally.

Or is it that you want to interleave on them in case they might add memory later (and the interleave would only take affect on a later memory allocation)

**Comment by gmprice** [comment]
The latter, I would like to be able to generally apply _any memory policy_ to memory-less nodes with the _assumption_ that memory will be added at some later point in time.

**Comment by andikleen** [comment]
I changed the code to report 0 for empty nodes (hope this won't break anything) and also not skip empty nodes. Let me know if there are still problems.
