### ISSUE TITLE
numactl can not move a task onto isolated cpus

### ISSUE THREAD

**Issue by pfliu** [numactl/numactl#186]
E.g. on a 16-cpus SMP system, isolating two cpus by the command line   grubby --args="isolcpus=14,15" --update-kernel=DEFAULT

Running the command:
   numactl --physcpubind=14,15 echo hello
Rendering the following result:
> libnuma: Warning: cpu argument 3 is out of range
> 
> <3> is invalid
> usage: numactl [--all | -a] [--balancing | -b] [--interleave= | -i <nodes>]
>                 [--preferred= | -p <node>] [--preferred-many= | -P <nodes>]
>                [--physcpubind= | -C <cpus>] [--cpunodebind= | -N <nodes>]
>                [--membind= | -m <nodes>] [--localalloc | -l] command args ...
>                [--localalloc | -l] command args ...
>        numactl [--show | -s]
>        numactl [--hardware | -H]

But if using "taskset --cpu-list 14,15 numactl --physcpubind=14,15 echo hello", it works.

My question is whether numactl should be entitled the same ability as taskset, despite of its own cpu affinity.

Thanks

**Comment by luochenglcs** [comment]
You can try to add option `--all`， does this meet your requirements?

**Comment by pfliu** [comment]
@luochenglcs, ah, it can meet my requirements. Thanks!

**Comment by pfliu** [comment]
It is not an issue, close it
