### ISSUE TITLE
URL in GitHub descriptions redirects to HPE

### ISSUE THREAD

**Issue by paulmenzel** [numactl/numactl#19]
The URL http://oss.sgi.com/projects/libnuma/ from the GitHub description redirects to https://www.hpe.com/us/en/solutions/hpc-high-performance-computing.html. Is that wanted?

**Comment by andikleen** [comment]
On Fri, Mar 02, 2018 at 07:34:55AM -0800, Paul Menzel wrote:
> The URL http://oss.sgi.com/projects/libnuma/ from the GitHub description
> redirects to https://www.hpe.com/us/en/solutions/
> hpc-high-performance-computing.html. Is that wanted?

Thanks for letting us know. I removed the URL

-Andi

**Comment by filbranden** [comment]
cc @cpwickman in case there's a new URL to update here. Closing, as it's fixed.
