### ISSUE TITLE
Can I be the committer of this project?

### ISSUE THREAD

**Issue by luochenglcs** [numactl/numactl#192]
I've been following and contributing to this project. In addition, I've submitted 27 patches and fixed a lot of issues.

**Comment by andikleen** [comment]
Sure I added you. Welcome to the team!

**Comment by luochenglcs** [comment]
@andikleen There are some commits and issues that haven't been processed for a long time, i have already replied to issues and reviewed commits. Is there anything else I can do?

**Comment by luochenglcs** [comment]
Can I become a maintainer?

**Comment by andikleen** [comment]
I think i added you. Let me know if it doesn't work. Sorry for the late answer.

BTW I would like to do a new release soon. Any testing in your environment would be appreciated.

**Comment by luochenglcs** [comment]
OK, I Can find machine and test it.

**Comment by luochenglcs** [comment]
I guess i don't have write permissions so I can't merge the pull request.

**Comment by andikleen** [comment]
You should have role maintain according to the settings. Not sure if it sent out an email though. Perhaps do a pull request yourself and try it.

**Comment by luochenglcs** [comment]
Maybe there's a mistake in the email address, please add me using luochunsheng@ustc.edu.

**Comment by luochenglcs** [comment]
@andikleen Please check it, thinks.

**Comment by andikleen** [comment]
I created a new invite. Please accept it.

**Comment by luochenglcs** [comment]
Thanks, I have received the invitation email and accepted it.
