### ISSUE TITLE
Reference actions by commit SHA

### ISSUE THREAD

**Issue by gabibguti** [numactl/numactl#193]
Referencing actions by commit SHA in GitHub workflows guarantees you are using an immutable version. Actions referenced by tags and branches are more vulnerable to attacks, such as the tag being moved to a malicious commit or a malicious commit being pushed to the branch.

Although there are pros and cons for each reference, GitHub understands [using commit SHAs is more reliable](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#using-shas), specially for actions developed by other users. [Scorecard](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies) security tool also recommends versioning by SHAs.

This would change, for example, `marvinpinto/action-automatic-releases@v1.2.1` to `marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0` followed by a comment `# v1.2.1` to keep the version readable. If you agree, I can support you by opening a PR.

##### Additional Context

Hi again! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by gabibguti** [comment]
Hey! Friendly ping here. Do you think it would be useful to reference actions by commit SHA? If there's no response, I will understand this may not be planned for now and I will close the issue in 2 months to avoid flooding the issues tab.

**Comment by andikleen** [comment]
Sorry for the late reply. I did the change. I think that was the only one from a not github owned repository. I assume the github ones don't need it? If something is missing please send a PR. Thanks!
