### ISSUE TITLE
usage of mbind, "maxnode" argument

### ISSUE THREAD

**Issue by fukien** [numactl/numactl#194]
Hi, 
I am browsing the codes under the "test/" directory, and have a question regarding how to call "mbind".

At https://github.com/numactl/numactl/blob/master/test/mbind_mig_pages.c#L93, the "maxnode" argument is passed as "old_nodes->size + 1".
However, at https://github.com/numactl/numactl/blob/master/test/prefered.c#L44, the "maxnode" argument is simply passed as "nodes->size".
Could anyone please tell me that why there is an "adding one" difference in these two example codes? 

Thank you.

**Comment by luochenglcs** [comment]
https://man7.org/linux/man-pages/man2/mbind.2.html
Explained in the man manual, maxnode gives the number of significant bits in nodemask. 

however, In the kernel, maxnode is decremented first, and then the bitmask is taken. I think this is very unreasonable.
so maxnode  = `the number of significant bits in nodemask` + 1.

Kernel code: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/mm/mempolicy.c?h=v4.19.296 + line 1309
```c
static int get_nodes(nodemask_t *nodes, const unsigned long __user *nmask,
		     unsigned long maxnode)
{
       ....
	--maxnode;  //decrease
       ....
	nlongs = BITS_TO_LONGS(maxnode);
	if ((maxnode % BITS_PER_LONG) == 0)
		endmask = ~0UL;
	else
		endmask = (1UL << (maxnode % BITS_PER_LONG)) - 1;  //get nmask endmask
       ....
       nodes_addr(*nodes)[nlongs-1] &= endmask;
       return 0；
```

**Comment by luochenglcs** [comment]
In [test/mbind_mig_pages.c#L93](https://github.com/numactl/numactl/blob/master/test/mbind_mig_pages.c#L93), `old_nodes->size` = `Number of existing nodes in the current environment`,  so it must need plus 1.

In [test/prefered.c#L44](https://github.com/numactl/numactl/blob/master/test/prefered.c#L44),  nodes->size = `Maximum nodes number of  supported by the operating system`, it‘s larger than `Number of existing nodes in the current environment`, So it don't worry about this, but I think `nodes->size + 1` also is OK.
