### ISSUE TITLE
Potential Bug: memcpy using msize/2 but using msize for performance calculation

### ISSUE THREAD

**Issue by HShamimGEHC** [numactl/numactl#200]
In Line 203, We are calling memcpy with an allocation size of msize/2: memcpy(mem, mem + msize/2, msize/2);

However, when calculating the performance and bandwidth, the size we use to make that calculation is msize:

Line 264: #define H(t) (((double)msize) / ((double)t))

Am I missing something here?

**Comment by luochenglcs** [comment]
For memory operations, (msize/2)/t is reasonable because memcpy has two operations: memory reads and memory writes. However, for memcpy operations, this is a miscalculation.

**Comment by HShamimGEHC** [comment]
So if I solely care about the memcpy operation and what its doing, for me, H(t) should be modified to msize/2 / t?

**Comment by luochenglcs** [comment]
Yes, I think so.

**Comment by andikleen** [comment]
Thanks for the analysis. I fixed it now by dividing msize by 2 in this case.
