### ISSUE TITLE
EINVAL for numa_set_schedaffinity 

### ISSUE THREAD

**Issue by andikleen** [numactl/numactl#204]
FAIL: test/bind_range

strace ./numactl --all --physcpubind=110 ls
sched_setaffinity(0, 16, [110])         = -1 EINVAL (Invalid argument)

The system has 112 CPUs so that should have worked.

**Comment by luochenglcs** [comment]
It seems to be caused by an error in the second parameter `cpusetsize`.

**Comment by luochenglcs** [comment]
Are you sure all CPUs are online? especially CPU-110.

**Comment by andikleen** [comment]
On Wed, Jan 17, 2024 at 12:01:32AM -0800, bookman wrote:
> Are you sure all CPUs are online? especially CPU-110.

Yes that's the problem. I only checked lscpu earlier, but it looks like
it doesn't check the individual online status. After onlining everything
the check passes
