### ISSUE TITLE
suppress printing "libnuma.c: Success"

### ISSUE THREAD

**Issue by ajaypanyala** [numactl/numactl#206]
Hello,

I have built the latest numactl from sources. A simple test program with the following lines prints 
`libnuma.c: Success` in the output. Am not sure where this print is coming from. Can it be suppressed ?

```
      numa_set_bind_policy(1);
      struct bitmask* numaNodes = numa_get_mems_allowed();
      numa_bind(numaNodes);
      int  numa_id         = numa_preferred();
```

**Comment by luochenglcs** [comment]
In numa_preferred(), when errno is 0, numa_error(__FILE__) will print "libnuma.c: Success" ，this doesn't meet expectations.

**Comment by andikleen** [comment]
Patch merged
