### ISSUE TITLE
better handling of CONFIG_NUMA=n / get_mempolicy: Function not implemented

### ISSUE THREAD

**Issue by nekopsykose** [numactl/numactl#212]
mostly the same thing as #208 , but i opened a new issue to not post in a closed one.

this happens because CONFIG_NUMA is disabled, but could it still be handled better?  

for example, procps-ng tries to load libnuma if it's present (https://gitlab.com/procps-ng/procps/-/blob/3aa2a49f0e066e3342599e20316b41ede22cce50/library/numa.c#L72), and then upon doing that it will immediately print this warning even when it was intentional to not have numa support (e.g. perhaps some virtualization-only kconfig).  

it's likely when using distro packages to need to install procps to use `ps`, and then also install programs that pull in `libnuma` via their dependency tree, and then on any use of `ps` this warning will be repeatedly printed. and as far as i can tell, procps cannot really even do anything about it- it's not a catchable error and the code that prints this runs as a library constructor upon loading libnuma itself. the only thing it could do is check if numa support exists in the kernel (`/sys/devices/system/node` ?) and only load libnuma if it was found? it seems a bit much for consumers to not have console warnings printed

**Comment by nekopsykose** [comment]
some other instances where the same happens is e.g. when using `perf` or `x265` or similar. in a distro build, those would link to libnuma (to add support for numa-related things when available), but inadvertantly this means using any of them on a kernel with numa disabled now prints warnings. this used to not be the case, even if it's silently unused at runtime (which is ok)

**Comment by nekopsykose** [comment]
the general way most libraries deal with this is require you to call something like `libnuma_init()` and return an error if it failed. then consumers can print something, or ignore it, .. . running `numa_init` [as a constructor](https://github.com/numactl/numactl/blob/8f2ffc89654cd3d26ae3ff9bd0a6f8354de9ec22/libnuma.c#L95) prevents doing any of that, so consumers have no choice and no ability to work around this at runtime themselves

**Comment by andikleen** [comment]
Yes we shouldn't print warnings from the constructor.

**Comment by nekopsykose** [comment]
thanks!
