### ISSUE TITLE
Fallback for `__NR_set_mempolicy_home_node` for architecture `__arm__` is missing

### ISSUE THREAD

**Issue by eschnett** [numactl/numactl#219]
The file `syscall.c` contains in line 144 fallback definitions for many architectures. The architecture `__arm__` is missing there.

**Comment by andikleen** [comment]
On Fri, May 10, 2024 at 10:53:13AM -0700, Erik Schnetter wrote:
> The file syscall.c contains in line 144 fallback definitions for many
> architectures. The architecture __arm__ is missing there.

Normally we only add it when the architecture has a real numa system in
use.  Are there arm (vs arm64) NUMA systems in use?

-Andi

**Comment by eschnett** [comment]
I don't know, probably not...

However, this is a build error on 32-bit ARM architectures. Earlier versions of numactl used to build, and newer versions don't build any more (when the Linux kernel headers are not installed).

I noticed the build error here https://github.com/JuliaPackaging/Yggdrasil/pull/8649 while building binaries for numactl 2.0.18.
