### ISSUE TITLE
Any plan for a new release?

### ISSUE THREAD

**Issue by honggyukim** [numactl/numactl#229]
The latest release 2.0.18 was 6 months ago and maybe @gmprice and I have some interests regarding a new release with the addition of `-w`/`--weighted-interleave` option.

I would like people to use some specific version of numactl for `--weighted-interleave` option but it's not ready yet so I would like to ask numactl make a new release. Thanks.

**Comment by nater1983** [comment]
I second a new release please.

**Comment by andikleen** [comment]
I released 2.0.19

**Comment by honggyukim** [comment]
Thanks @andikleen!

**Comment by nater1983** [comment]
Thank you.
