### ISSUE TITLE
numactl exits if MPOL_PREFERRED_MANY isn't supported

### ISSUE THREAD

**Issue by notgwj** [numactl/numactl#231]
On startup libnuma [checks](https://github.com/numactl/numactl/blob/master/libnuma.c#L644) for `MPOL_PREFERRED_MANY` support.  If `MPOL_PREFERRED_MANY` is not supported `errno` gets set.  `numactl` exits if `errno` is set here: https://github.com/numactl/numactl/blob/master/numactl.c#L630.

Our local fix is to add an else clause to the `if` in [libnuma.c](https://github.com/numactl/numactl/blob/master/libnuma.c#L648) that clears errno.

```
	if (set_mempolicy(MPOL_PREFERRED_MANY, tmp->maskp, tmp->size) == 0) {
		has_preferred_many = 1;
		/* reset the old memory policy ignoring error */
		(void)set_mempolicy(oldp, bmp->maskp, bmp->size+1);
	} else {
		/* Clear errno from failed set_mempolicy() call */
		errno = 0;
	}
```

**Comment by andikleen** [comment]
Thanks. I fixed it slightly differently by saving/restoring errno. This _MANY patchkit was certainly quite problematic.
