### ISSUE TITLE
libnuma license?

### ISSUE THREAD

**Issue by softerhardware** [numactl/numactl#234]
At the top of libnuma.c, the license is LGPL. But at line 144 libnuma.c there is the following comment:

/*
 * The following bitmask declarations, bitmask_*() routines, and associated
 * _setbit() and _getbit() routines are:
 * Copyright (c) 2004_2007 Silicon Graphics, Inc. (SGI) All rights reserved.
 * SGI publishes it under the terms of the GNU General Public License, v2,
 * as published by the Free Software Foundation.
 */

https://github.com/numactl/numactl/blob/master/libnuma.c

What is the license of libnuma.c? Do these routines taint the entire library and make it GPL? Legal review is saying that the library is GPL due to inclusion of this GPL code and therefore we can't use the library.

Thanks,

Steve Haynal

**Comment by andikleen** [comment]
I checked with Cliff Wickman, the author of the GPLed hunks and he is fine with changing them to LGPL.

Will push that change soonish.
