### ISSUE TITLE
Is there a plan to provide an API for weighted interleaving through libnuma?

### ISSUE THREAD

**Issue by MatthiasKohl** [numactl/numactl#237]
Release 2.0.19 of `numactl` contains the new `--weighted-interleave` option, see https://github.com/numactl/numactl/issues/229.
As far as I can tell, there is no API for a specific allocation to be distributed in weighted interleave mode, in `libnuma`.

There is `numa_alloc_interleaved`, but no `numa_alloc_weighted_interleaved` or similar.
Is there a plan to add such an API?
I'm not sure whether this is the right place to ask this question, let me know if it's not.

**Comment by honggyukim** [comment]
Hi, we can work on this if you and @gmprice are okay. My colleague @hygoni can prepare for a PR next week.

**Comment by MatthiasKohl** [comment]
That sounds great! 
Our use case is one where a single large allocation (or few large allocations) should be interleaved with weights, but not the entire process memory. This is to avoid "hot memory" going to the other NUMA nodes, which would significantly increase latencies.
It would be great if you can work on this

**Comment by andikleen** [comment]
On Fri, Dec 06, 2024 at 01:42:02PM -0800, Honggyu Kim wrote:
> Hi, we can work on this if you and @gmprice are okay. My colleague @hygoni can
> prepare for a PR next week.

Sure please go ahead.

**Comment by honggyukim** [comment]
Thanks for the confirmation. @hygoni Please send a PR when you're ready.

**Comment by hygoni** [comment]
> Thanks for the confirmation. @hygoni Please send a PR when you're ready.

Just have sent PR #238. Thanks!

**Comment by honggyukim** [comment]
@hygoni Thanks for the PR!

@MatthiasKohl You can use his PR for the `numa_alloc_weighted_interleaved`, but I would like suggest one more option for your usecase. We're developling another heterogeneous memory allocator called `hmalloc` with `hmctl` tool, which is similar to `numactl`, but it only applies memory policy to the memory area, which is allocated by hmalloc family allocation APIs.

There are some pros and cons using hmalloc compared to using `numa_alloc_weighted_interleaved`.

1. It can do object level allocation using [hmalloc APIs](https://github.com/skhynix/hmsdk/wiki/hmalloc#hmalloc-apis) while `numa_alloc_weighted_interleaved` can only do `mmap` internally. The object arena is internally managed by jemalloc.

2. If you run weighted interleave in a machine with more than 2 sockets, the weights depend on which socket tries to access the memory node. So you can use `numa_alloc_weighted_interleaved_subset`, but it requires to have `nodemask`. But using `hmalloc` with `hmctl` makes you free from hard coding `nodemask` in your program.

This is out of topic but if you're interested, then I would be happy to explain more about it at https://github.com/skhynix/hmsdk/issues.

**Comment by MatthiasKohl** [comment]
@honggyukim interesting, thank you for the pointers!
