### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by TBK** [numactl/numactl#27]
Would it be possible to make a new release?

**Comment by filbranden** [comment]
Planning to... Just haven't gotten around to it yet... I might be able to carve out some time to do that early next week. (And also sort out download site which has been down for a while.) Hang on! :smiley:

**Comment by TBK** [comment]
Super 👍

**Comment by filbranden** [comment]
2.0.12 released!

Announcement here: https://www.spinics.net/lists/linux-numa/msg01178.html

Download here: https://github.com/numactl/numactl/releases/download/v2.0.12/numactl-2.0.12.tar.gz
