### ISSUE TITLE
numactl --membind not working?

### ISSUE THREAD

**Issue by hc128168** [numactl/numactl#45]
Hi,

I am new to NUMA stuffs.  Hope that I don't raise a bogus bug.

I started my script with taskset and numactl:
```
$ taskset -c 19 numactl --membind=1 bash spin.sh &
[1] 98621
```
However, numastat indicated that some of the memory wasn't allocated on node 1:
```
$ sudo numastat -p 98621

Per-node process memory usage (in MBs) for PID 98621 (bash)
                           Node 0          Node 1           Total
                  --------------- --------------- ---------------
Huge                         0.00            0.00            0.00
Heap                         0.00            0.03            0.03
Stack                        0.00            0.02            0.02
Private                      1.14            0.13            1.27
----------------  --------------- --------------- ---------------
Total                        1.14            0.18            1.32
```
Is it expected?  What does "private" mean?  "Private" to process right?

spin.sh is very simple:
```
i=0
while true; do
        i=i+1
done
```
Thanks!

**Comment by hc128168** [comment]
numactl has no bug.  Just how linux works in loading stuffs.

Tho, I am still curious what "Private" means there.

**Comment by pinconsolable** [comment]
@hc128168 Hi, any idea for this `Private` part? I saw that different os displays different here, I also confused about the Private part. Thanks
