### ISSUE TITLE
Unused variable 'loose' in memhog.c

### ISSUE THREAD

**Issue by sanskriti-s** [numactl/numactl#50]
In memhog.c, the variable loose is iniltialzed to 0. It is then set to 1 in an else statement on [line 105 ](https://github.com/numactl/numactl/blob/master/memhog.c#L105). However, the connected if statement includes an exit. Thus if the program doesn't exit, it sets loose =1. Therefore, the usage of loose in [lines 132 ](https://github.com/numactl/numactl/blob/master/memhog.c#L132) and [136 ](https://github.com/numactl/numactl/blob/master/memhog.c#L136) are redundant. Should loose be completely removed or does it serve some purpose that is now broken?

**Comment by andikleen** [comment]
I guess the exit(1) in the check is wrong. The idea was to be able to run it without NUMA support.
