### ISSUE TITLE
Poor diagnostic message when kernel adds new fields to meminfo

### ISSUE THREAD

**Issue by aegl** [numactl/numactl#58]
When the node specific meminfo files have field(s) that numastat doesn't know about it prints the cryptic message:

"Token Node not in hash table."

It would be more helpful to print the token that is missing, rather than the first token on the line (typically the word "Node").

$ diff orig-numastat.c numastat.c
827c827
<                               printf("Token %s not in hash table.\n", tok[0]);
---
>                               printf("Token %s not in hash table.\n", tok[0 + tok_offset]);

**Comment by andikleen** [comment]
On Wed, Jan 23, 2019 at 12:51:58PM -0800, aegl wrote:
> When the node specific meminfo files have field(s) that numastat doesn't know
> about it prints the cryptic message:
> 
> "Token Node not in hash table."
> 
> It would be more helpful to print the token that is missing, rather than the
> first token on the line (typically the word "Node").
> 
> $ diff orig-numastat.c numastat.c
> 827c827
> < printf("Token %s not in hash table.\n", tok[0]);
> 
>                               printf("Token %s not in hash table.\n", tok[0 + tok_offset]);
> 

Can you send a pull request please?

**Comment by andikleen** [comment]
fixed
