### ISSUE TITLE
Adding the license file

### ISSUE THREAD

**Issue by jakirkham** [numactl/numactl#68]
It appears the license file (or files) are missing from this repo. Could we please include them? This is important both for people auditing their dependencies and package repos relaying this information to their users.

**Comment by jakirkham** [comment]
Friendly nudge 😉

**Comment by andikleen** [comment]
Well it has the standard GPL headers in nearly all source files, which have a pointer to the GPL.
Is adding a full copy of the GPL really helping?

**Comment by jakirkham** [comment]
GNU certainly [thinks so]( https://www.gnu.org/licenses/gpl-faq.en.html#WhyMustIInclude ). Many packaging distros [require it]( https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/rpm_packaging_guide/index#preparing-source-code-for-packaging ). Though I may be missing something, what is the concern with adding the license file?

**Comment by andikleen** [comment]
On Mon, Aug 19, 2019 at 05:04:44PM -0700, jakirkham wrote:
> GNU certainly thinks so. Many packaging distros require it. Though I may be
> missing something, what is the concern with adding the license file?

Just seems redundant. I'm sure every Linux system already has multiple
copies. Your copyright scanner should be looking at the source code
headers anyways because even if a COPYING file was in there some source
files might be licensed under other licenses.

**Comment by filbranden** [comment]
I do agree we should add the license text.

Many compliance tools rely on that. Also, it's not great to say this code is licensed under the GPL when we don't really specify what the GPL is (it could be "greatly proprietary license", no?)

Anyways, filed #75 to include the license files, assigned it to @andikleen.

Thanks!
Filipe
