### ISSUE TITLE
why not support openwrt?

### ISSUE THREAD

**Issue by liudf0716** [numactl/numactl#71]
does anyone add package for openwrt?

**Comment by filbranden** [comment]
This is the upstream for numactl... We provide dist tarballs that should compile in most Linux systems...

Maybe you should contact OpenWRT about them packaging this for their systems?

Though OpenWRT is typically meant to run on very small embedded systems... And libnuma is mostly about large systems with more than one memory/cpu nodes... So maybe not a great match?

Anyways, not really something we can do here... I suggest you contact OpenWRT or the OpenWRT communities about packaging this code for those systems, if they have interest in it.

**Comment by zokl** [comment]
Try this package: https://github.com/k13132/openwrt-dpdk/tree/main/packages/numactl

**Comment by liudf0716** [comment]
@zokl thanks
