### ISSUE TITLE
How to submit patch for numactl?

### ISSUE THREAD

**Issue by csqshz** [numactl/numactl#78]
Is there mail list?

On github, I find Pull requests is 0, but https://travis-ci.org/numactl/numactl/pull_requests is active.
But I don't know how to send patch to https://travis-ci.org/numactl/numactl/pull_requests.

@filbranden 

Thanks,
--Hongzhi

**Comment by csqshz** [comment]
I find linux-numa@xxxxxxx. Right?

**Comment by harish-24** [comment]
You can fork [this](https://github.com/numactl/numactl/) repository and create a new Pull Request out of your fork which is same for any other github project.

**Comment by csqshz** [comment]
I sent patch to  linux-numa@vger.kernel.org. If it don't work, I will create a Pull Request.
