### ISSUE TITLE
numactl man page has incorrect information about --localalloc option

### ISSUE THREAD

**Issue by roshanmangal** [numactl/numactl#81]
numactl man page has incorrect information about --localalloc option.

Current Text:-
       --localalloc, -l
              Always allocate on the current node.

It should be 

       --localalloc, -l
              Try to allocate on the current node of the process, but if memory cannot be allocated there fall back to other nodes.

**Comment by seeteena** [comment]
I have made this changes and raise a pull request - 

https://github.com/numactl/numactl/pull/88

**Comment by seeteena** [comment]
Fixed. We can close this issue now.
