### ISSUE TITLE
Low-priority memory leak

### ISSUE THREAD

**Issue by fireice-uk** [numactl/numactl#86]
If I understand the code correctly, this function https://github.com/numactl/numactl/blob/master/numactl.c#L228 leaks cpus bitmask.

**Comment by andikleen** [comment]
Well it doesn't matter because the code just exits afterwards.
I assume it could be cleaned up for valgrind's sake only.

**Comment by hyeongtakji** [comment]
Looks like this issue has been resolved by #189
