### ISSUE TITLE
Compile problem; not finding .libs/libnuma.so

### ISSUE THREAD

**Issue by markyoder** [numactl/numactl#89]
installation (make) cannot find `libnuma.so` . technically, the file does exist, but it is a broken link to nothing.

```
...
make  all-am
make[1]: Entering directory `/scratch/myoder96/Downloads/SeisSol/numactl'
  CC       numactl.o
  CC       util.o
  CC       shm.o
  CC       libnuma.lo
  CC       syscall.lo
  CC       distance.lo
  CC       affinity.lo
  CC       sysfs.lo
  CC       rtnetlink.lo
  CCLD     libnuma.la
  CCLD     numactl
icc: error #10236: File not found:  './.libs/libnuma.so'
make[1]: *** [numactl] Error 1
make[1]: Leaving directory `/scratch/
```

**Comment by torehl** [comment]
Install numactl-libs and numactl-libs-devel (RedHat/CentOS/Fedora)
or libnuma1:amd64 and libnuma1-dev:amd64  (Ubuntu/Debion/Mint etc)

$ rpm -qf /usr/lib64/libnuma.so.1.0.0
numactl-libs-2.0.12-3.fc31.x86_64

$ dpkg -S /usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
libnuma1:amd64: /usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0

--ToreL

**Comment by markyoder** [comment]
Thanks ToreL. -

I thought this was (at least part of) what I was installing. I'm trying to
set this up in an HPC environment, nominally using LMOD modules, but maybe
that is not necessary. I'll consult my sysadmin.

mark


Mark Yoder, PhD
805 451 8750
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"If you bore me, you lose your soul (to me)..."
~belly

**Comment by andikleen** [comment]
On Tue, Mar 24, 2020 at 05:47:34PM -0700, Mark R. Yoder, Ph.D. wrote:
> Thanks ToreL. -
> 
> I thought this was (at least part of) what I was installing. I'm trying to
> set this up in an HPC environment, nominally using LMOD modules, but maybe
> that is not necessary. I'll consult my sysadmin.

No you shouldn't need libnuma already installed, numactl contains it
Something must be wrong with the build procedure. 

Maybe wrong version of autoconf?

**Comment by markyoder** [comment]
looks like autoconf is 2.69

Thanks!

mark



Mark Yoder, PhD
805 451 8750
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"If you bore me, you lose your soul (to me)..."
~belly

**Comment by filbranden** [comment]
Hmmm looks like your compiler is `icc`, maybe the problem is related to that... Can you compile it using `gcc` instead? `gcc` is incredibly portable, I imagine it must be available for your platform... I don't really have access to `icc`, so not sure I can reproduce this issue myself...
