### ISSUE TITLE
Symbol versioning incompatibility with gcc 4.8.5

### ISSUE THREAD

**Issue by samcmill** [numactl/numactl#94]
In 2.0.14, the `SYMVER` macro escapes quotes.  For instance

`SYMVER("numa_sched_getaffinity_v2", "numa_sched_getaffinity@@libnuma_1.2")`
becomes
`__asm__ (".symver " "\"numa_sched_getaffinity_v2\"" "," "\"numa_sched_getaffinity@@libnuma_1.2\"");`

gcc 4.8.5, the default compiler on RHEL/CentOS 7, does not handle the escaped quotes:
```
/tmp/cckm8DwN.s: Assembler messages:
/tmp/cckm8DwN.s:3: Error: Missing symbol name in directive
/tmp/cckm8DwN.s:3: Error: expected comma after name in .symver
```

More recent compilers do not seem to have this limitation, e.g., gcc 8.3.1, handling the escaped quotes fine.

This change works for me on both 4.8.5 and 8.3.1:
```
--- a/util.h    2020-10-08 10:08:40.517167202 -0700
+++ b/util.h    2020-10-08 10:08:55.523301155 -0700
@@ -22,5 +22,5 @@
 #if HAVE_ATTRIBUTE_SYMVER
 #define SYMVER(a,b) __attribute__ ((symver (b)))
 #else
-#define SYMVER(a,b) __asm__ (".symver " #a "," #b);
+#define SYMVER(a,b) __asm__ (".symver " a "," b);
 #endif
```

**Comment by andikleen** [comment]
Thanks Scott. Looks good. Can you please submit a pull request with the fix?
