### ISSUE TITLE
How to show numerical differences in two numastat log files?

### ISSUE THREAD

**Issue by jirka-h** [numactl/numactl#96]
Hello,

I capture numastat logs before and after running a command like this:

```sh
numastat > numastat.start ; COMMAND; numastat > numastat.end
```

Is there a tool to show numerical differences between `numastat.end `and `numastat.start` files? I want to subtract the `end values` from the `start values` while keeping the file format. 

I'm thinking about writing a small tool in Python for that, but I don't want to reinvent the wheel. I think I'm not the first one who is trying to solve this:-) 

Any hint or advice? 

Below are the example files, for which I'm trying to compute the numerical differences. I'm using Google Sheet for it right now, but I'm looking for an automated way. 

Thanks a lot
Jirka

```sh
$ more numastat.0.start
                           node0           node1           node2           node3           node4           node5           node6           node7
numa_hit                 2941595         1849807         6654372         4838353        12229828         2819605         2426858         3311826
numa_miss                      0               0               0               0               0               0               0               0
numa_foreign                   0               0               0               0               0               0               0               0
interleave_hit             19833           19801           19837           19809           19825           19812           19835           19805
local_node               2932819         1822473         6632791         4811102        12191273         2792358         2399298         3278575
other_node                  8776           27334           21581           27251           38555           27247           27560           33251

$ more numastat.0.end
                           node0           node1           node2           node3           node4           node5           node6           node7
numa_hit                 2954256         1849828         6665977         4838617        12264020         2819647         2426858         3311826
numa_miss                      0               0               0               0               0               0               0               0
numa_foreign                   0               0               0               0               0               0               0               0
interleave_hit             19833           19801           19837           19809           19825           19812           19835           19805
local_node               2945472         1822494         6644392         4811366        12225461         2792400         2399298         3278575
other_node                  8784           27334           21585           27251           38559           27247           27560           33251

$ more numastat.0.diff (produced with help of Google Sheets, but I'm looking for a command-line utility to produce the same result. The side effect is that formatting is broken.)
	node0	node1	node2	node3	node4	node5	node6	node7
numa_hit	12661	21	11605	264	34192	42	0	0
numa_miss	0	0	0	0	0	0	0	0
numa_foreign	0	0	0	0	0	0	0	0
interleave_hit	0	0	0	0	0	0	0	0
local_node	12653	21	11601	264	34188	42	0	0
other_node	8	0	4	0	4	0	0	0
```

**Comment by andikleen** [comment]
On Tue, Nov 03, 2020 at 07:06:30PM -0800, jirka-h wrote:
> Hello,
> 
> I capture numastat logs before and after running a command like this:
> 
> numastat > numastat.start ; COMMAND; numastat > numastat.end
> 
> Is there a tool to show numerical differences between numastat.end and
> numastat.start files? I want to subtract the end values from the start values
> while keeping the file format.
> 
> I'm thinking about writing a small tool in Python for that, but I don't want to
> reinvent the wheel. I think I'm not the first one who is trying to solve
> this:-)
> 
> Any hint or advice?

I'm not aware of any existing tool for this.

It's probably simple enough in pandas.

-Andi

**Comment by jirka-h** [comment]
Thanks a lot for the hint to use pandas. It was indeed easy ;-) 

The script is [here.](https://github.com/jirka-h/numastat_diff)

Please consider to include it in the numactl. I would be honored. 

Thanks a lot!
Jirka

**Comment by berndfinger** [comment]
Or you can try this:
# awk 'FNR==NR{n++
   if (NR==0) {print}
   if (NR>0){
      for (i=1; i<=NF; i++) {
         a[(FNR)][i]=$(i+1);
      }
      next
   }
}
NR>(n+1){
   printf ("%-15s ", $1);
   for (i=1; i<=NF-1; i++) {
      printf ("%10d ", $(i+1)-a[(FNR)][i]);
   }
   printf ("\n");
}' numastat.start numastat.end

**Comment by jirka-h** [comment]
I like it! It can be handy when you don't have pandas at hand and it's run faster. On the other hand, pandas' solution is more robust. 

I have turned it into an awk script, added some basic checks, and [published it here.](https://github.com/jirka-h/numastat_diff/blob/main/Awk/numastat_diff.awk) 

Could we add any of these solutions to the numactl repository? I guess anybody using `numastat` would be interested to compute the differences of two `numastat` outputs, right?
